version: '3.4'


volumes:
  l1_data:


services:
  # L1
  #

  l1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8545:8545"
      - "8546:8546"
      - "7060:6060"
    volumes:
      - "l1_data:/db"
      - "${PWD}/genesis-l1.json:/genesis.json"
      - "${PWD}/test-jwt-secret.txt:/config/test-jwt-secret.txt"
    environment:
      GETH_MINER_RECOMMIT: 100ms