version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - /tmp/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=longsecretforseq
      - POSTGRES_USER=seq
      - POSTGRES_DB=seqdb