networks:
  avalanchelocal:
    ipam:
      driver: default
      config:
        - subnet: 177.17.0.0/24
  eth-pos-devnet_l1:
    external:
      true

services:
  avalanche-local-validator01:
    image: "ash/avalanche-node-local-validator01:${AVALANCHEGO_VERSION:-1.10.10}-${AVALANCHEGO_VM_NAME:-tokenvm}-${AVALANCHEGO_VM_VERSION:-0.0.999}"
    container_name: ash-avalanche-local-validator01
    ports:
      - "9650:9650"
      - "9651:9651"
    networks:
      eth-pos-devnet_l1:
      avalanchelocal:
        ipv4_address: 177.17.0.11
    volumes:
      - ./conf/bootstrap/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator02:
    image: "ash/avalanche-node-local-validator02:${AVALANCHEGO_VERSION:-1.10.10}-${AVALANCHEGO_VM_NAME:-tokenvm}-${AVALANCHEGO_VM_VERSION:-0.0.999}"
    container_name: ash-avalanche-local-validator02
    ports:
      - "9652:9650"
      - "9653:9651"
    networks:
      eth-pos-devnet_l1:
      avalanchelocal:
        ipv4_address: 177.17.0.12
    volumes:
      - ./conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator03:
    image: "ash/avalanche-node-local-validator03:${AVALANCHEGO_VERSION:-1.10.10}-${AVALANCHEGO_VM_NAME:-tokenvm}-${AVALANCHEGO_VM_VERSION:-0.0.999}"
    container_name: ash-avalanche-local-validator03
    ports:
      - "9654:9650"
      - "9655:9651"
    networks:
      eth-pos-devnet_l1:
      avalanchelocal:
        ipv4_address: 177.17.0.13
    volumes:
      - ./conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator04:
    image: "ash/avalanche-node-local-validator04:${AVALANCHEGO_VERSION:-1.10.10}-${AVALANCHEGO_VM_NAME:-tokenvm}-${AVALANCHEGO_VM_VERSION:-0.0.999}"
    container_name: ash-avalanche-local-validator04
    ports:
      - "9656:9650"
      - "9657:9651"
    networks:
      eth-pos-devnet_l1:
      avalanchelocal:
        ipv4_address: 177.17.0.14
    volumes:
      - ./conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  avalanche-local-validator05:
    image: "ash/avalanche-node-local-validator05:${AVALANCHEGO_VERSION:-1.10.10}-${AVALANCHEGO_VM_NAME:-tokenvm}-${AVALANCHEGO_VM_VERSION:-0.0.999}"
    container_name: ash-avalanche-local-validator05
    ports:
      - "9658:9650"
      - "9659:9651"
    networks:
      eth-pos-devnet_l1:
      avalanchelocal:
        ipv4_address: 177.17.0.15
    volumes:
      - ./conf/node/conf:/etc/avalanche/avalanchego/mounted-conf
  l1:
    build:
      context: ./eth-l1
      dockerfile: Dockerfile-l1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "7060:6060"
    volumes:
      - ./eth-l1/l1_data:/db
      - ./eth-l1/genesis-l1.json:/genesis.json
      - ./eth-l1/test-jwt-secret.txt:/config/test-jwt-secret.txt
    environment:
      GETH_MINER_RECOMMIT: 100ms
    networks:
      avalanchelocal:
        ipv4_address: 177.17.0.10
