# Copyright (C) 2023, Ava Labs, Inc. All rights reserved.
# See the file LICENSE for licensing terms.

name: SEQ Load Tests

on:
  push:
    branches:
      - main
  #pull_request:
    #types: [labeled,synchronize,reopened]

jobs:
  seq-load-tests:
    #if: ${{ github.ref == 'refs/heads/main' || contains(github.event.pull_request.labels.*.name, 'run load') }}
    strategy:
      matrix:
        level: [v1, v2, v3] # v4 is not supported
    runs-on:
      labels: ubuntu-20.04
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"
          check-latest: true
          cache: true
          cache-dependency-path: |
            go.sum
      - name: Run load tests
        shell: bash
        run: GOAMD64=${{ matrix.level }} scripts/tests.load_msg.sh
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
